name: single_import_generator
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/Xim-ya/single_import_generator

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  args: ^2.4.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

executables:
  barrel_export:
    script: bin/barrel_export.dart
  annotation_export:
    script: bin/annotation_export.dart

