name: single_import_generator
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Xim-ya/single_import_generator

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  source_gen: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

executables:
  barrel_export:
    script: bin/barrel_export.dart

  barrel_export_all:
    script: bin/barrel_export_all.dart