name: single_import_generator
description: Consolidate import statements and improve code organization with Single Import Generator, a command-line tool for Dart projects.
version: 1.0.0
homepage: https://github.com/Xim-ya/single_import_generator

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter






